final folders = [
  'lib/app/config',
  'lib/app/core',
  'lib/app/extensions',
  'lib/app/shared_widgets',
  'lib/app/utils',
  'lib/data',
  'lib/data/models',
  'lib/data/provider',
  'lib/data/provider/network',
  'lib/data/repositories',
  'lib/modules/home/notifiers',
  'lib/modules/home/views',
  'lib/modules/home/providers',
  'lib/app/routes',
];
